services:
  imadds:
    build:
      context: .
    networks:
      - imadds-network
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  imadds-network: